kafka:
  bootstrap-servers: localhost:9092
  group:
    id: test-consumer-group
  topic:
    poc: poc

rabbit:
  queueName: poc
  exchangeName: poce

server:
  port: 0
spring:
  data:
    cassandra:
      keyspace-name: poc
#      contact-points: 192.168.107.170

