kafka:
  bootstrap-servers: localhost:9092
  group:
    id: test-consumer-group
  topic:
    poc: poc

rabbit:
  queue: poc

server:
  port: 9090
spring:
  data:
    cassandra:
      keyspace-name: poc

